[[redirects]]
  from = "https://www.heilpraxis-koenig.de/*"
  to = "https://koenido.github.io"
  status = 301
  force = true

[[redirects]]
  from = "https://heilpraxis-koenig.de/*"
  to = "https://koenido.github.io"
  status = 301
  force = true

[[redirects]]
  from = "https://status.heilpraxis-koenig.de/*"
  to = "https://stats.uptimerobot.com/FoMY4Lqvgh"
  status = 301
  force = true

